language: node_js
node_js:
 - "8"

script: "./travis.sh"

before_install:
  - npm i -g @google/clasp

env:
  global:
    secure: SX8cffpSHIcxKk9kUpl9rEdQuZWzfGL3BNYzxFUS+AKeOsr3A+Kqf4VWQYb1s+Zit4V5ePalrzk9lxVOkiJ95Ou6zEHyOzvf4wL/rqwB0Z68ZxsLkWqUlmPlxiknTiOW2fc79D9mpiAy2IMUAnCwY6XolFV1dRbsXhFp/G3sMSUjzE+6iDa+LwU8MVEiksUcogCwF/qsCV/WkmZSRh3fuzUIhhhqBuVh7/beRF/pcjeFbthtCdO1WvYFdohgZEbpIazVncFY7i20FrkOlO5K7YEqbwjXnyIqeRicT+hr0N/XhjKefkTxfiQlIzdvO5VbbtIYEQjzY+M6NBbOnWoy4Di9SEE8YTsn8tgYDrPzlV6yrDJFx5iuhrisOURE1xdaQY2FyOwSnb1oLFZgqgdj9vyG0LpTm7qRmUrSayiZ2OkzRg7J7qZcAAj46IVC2q2YE8lN53BZAKi2WmhOCMkqhPRWmtIm8FpmFMe3xctoYiteIDlNVbFEjhe4QWLGcNou0+oBYj1ewHqje37FljdrgwY6O0HdtmfsXYA6WVgUjypL5cNl17c2vEByY+1yeRf7UPhlyxCuXlif0wjaKQa6Xr0F2BSIV68JNQiQoKwwBvosplmsM8gFJEF1iSpHuHtOoKLkt1j04gM3IKXllkI278VvnU7RBBs3cN+WI2Tfpfg=
